/* eslint-disable */
// AUTO-GENERATED by scripts/generate-contract-errors.js — DO NOT EDIT.
// Source of truth: packages/contracts/*/src/errors.rs
// Regenerate with: pnpm --filter backend generate:contract-errors

export interface ContractErrorDefinition {
  code: number;
  name: string;
  message: string;
}

export interface ContractErrorEnum {
  /** Rust crate directory under packages/contracts. */
  contract: string;
  /** Rust `#[contracterror]` enum name. */
  enumName: string;
  errors: Readonly<Record<number, ContractErrorDefinition>>;
}

export const CONTRACT_ERROR_REGISTRY: Readonly<
  Record<string, ContractErrorEnum>
> = {
  backit_token: {
    contract: 'backit_token',
    enumName: 'BackitError',
    errors: {
      1: {
        code: 1,
        name: 'AlreadyInitialized',
        message: 'Initialize called on an already-initialised contract.',
      },
      2: {
        code: 2,
        name: 'NotInitialized',
        message:
          'A function requiring initialisation was called before initialize.',
      },
      3: {
        code: 3,
        name: 'Unauthorized',
        message: 'Caller is not authorised for this operation.',
      },
      4: {
        code: 4,
        name: 'ZeroBalance',
        message:
          'The holder has no tokens and therefore no revenue share to claim.',
      },
      5: {
        code: 5,
        name: 'NoFeesAvailable',
        message: 'The fee pool is empty — nothing to distribute.',
      },
      6: {
        code: 6,
        name: 'AlreadyStaked',
        message: 'The staker already has an active stake.',
      },
      7: {
        code: 7,
        name: 'NotStaked',
        message: 'No active stake found for this address.',
      },
      8: {
        code: 8,
        name: 'LockNotExpired',
        message: 'The stake lock period has not yet expired.',
      },
      9: {
        code: 9,
        name: 'InvalidAmount',
        message: 'Amount is invalid (zero or negative).',
      },
      10: {
        code: 10,
        name: 'InsufficientBalance',
        message: 'Insufficient token balance for the requested operation.',
      },
      11: {
        code: 11,
        name: 'InvalidLockDuration',
        message: 'Lock duration provided is zero.',
      },
      12: {
        code: 12,
        name: 'UsdcNotConfigured',
        message: 'USDC SAC address has not been configured.',
      },
    },
  },
  call_registry: {
    contract: 'call_registry',
    enumName: 'CallRegistryError',
    errors: {
      1: {
        code: 1,
        name: 'AlreadyInitialized',
        message: 'Initialize was called on an already-initialised contract.',
      },
      2: {
        code: 2,
        name: 'NotInitialized',
        message:
          'A function that requires the contract to be initialised was called before initialize.',
      },
      3: {
        code: 3,
        name: 'InvalidStakeAmount',
        message: 'stake_amount (or the amount passed to stake_on_call) is ≤ 0.',
      },
      4: {
        code: 4,
        name: 'InvalidEndTime',
        message:
          'end_ts is not strictly in the future relative to the current ledger timestamp.',
      },
      5: {
        code: 5,
        name: 'CallNotFound',
        message: 'No call exists for the supplied call_id.',
      },
      6: {
        code: 6,
        name: 'CallEnded',
        message:
          "The call's end_ts has already passed; staking is no longer allowed.",
      },
      7: {
        code: 7,
        name: 'CallSettled',
        message: 'The call has already been settled; the operation is a no-op.',
      },
      8: {
        code: 8,
        name: 'InvalidPosition',
        message: 'Position is not 1 (UP) or 2 (DOWN).',
      },
      9: {
        code: 9,
        name: 'Unauthorized',
        message:
          'The caller does not hold the required role (admin / outcome_manager).',
      },
      10: {
        code: 10,
        name: 'ContractPaused',
        message:
          'Reserved for a future pause mechanism; no operations are permitted while paused.',
      },
      11: {
        code: 11,
        name: 'CallNotEnded',
        message: 'resolve_call was called before end_ts has passed.',
      },
      12: {
        code: 12,
        name: 'InvalidOutcome',
        message: 'Outcome passed to resolve_call is not 1 (UP) or 2 (DOWN).',
      },
      13: {
        code: 13,
        name: 'InvalidOutcomeCount',
        message: 'outcome_count is less than 2.',
      },
      14: {
        code: 14,
        name: 'FeeTooHigh',
        message: 'fee_bps exceeds 10 000 (100 %).',
      },
      15: {
        code: 15,
        name: 'StakingCutoffActive',
        message: 'Staking attempted within the cutoff window before end_ts.',
      },
      16: {
        code: 16,
        name: 'Sep10TokenExpired',
        message: "The SEP-10 token's valid_until ledger sequence has passed.",
      },
      17: {
        code: 17,
        name: 'ReentrancyDetected',
        message: 'Re-entrant call detected on a guarded function.',
      },
      18: {
        code: 18,
        name: 'Overflow',
        message:
          'A checked arithmetic operation (multiplication, division, addition, or subtraction) would have overflowed/underflowed or divided by zero. Raised by the reputation-weighted stake-limit calculations and any other checked-math call sites in this crate.',
      },
      20: {
        code: 20,
        name: 'NotFound',
        message:
          'Generic not found error for requested entity (e.g., proposal).',
      },
      21: {
        code: 21,
        name: 'InvalidInput',
        message: 'Invalid input was provided to the operation.',
      },
      22: {
        code: 22,
        name: 'NotReady',
        message:
          'The operation is not ready to be executed yet (timelock not expired).',
      },
    },
  },
  charity_markets: {
    contract: 'charity_markets',
    enumName: 'CharityError',
    errors: {
      1: { code: 1, name: 'NotInitialized', message: 'Not initialized.' },
      2: {
        code: 2,
        name: 'AlreadyInitialized',
        message: 'Already initialized.',
      },
      3: { code: 3, name: 'Unauthorized', message: 'Unauthorized.' },
      4: { code: 4, name: 'InvalidCharity', message: 'Invalid charity.' },
      5: { code: 5, name: 'AlreadyResolved', message: 'Already resolved.' },
      6: {
        code: 6,
        name: 'CharitySplitExceedsMax',
        message: 'Charity split exceeds max.',
      },
      7: { code: 7, name: 'CallNotFound', message: 'Call not found.' },
      8: { code: 8, name: 'InvalidOutcome', message: 'Invalid outcome.' },
      9: {
        code: 9,
        name: 'InvalidStakeAmount',
        message: 'Invalid stake amount.',
      },
      10: { code: 10, name: 'InvalidCallId', message: 'Invalid call id.' },
      11: { code: 11, name: 'ZeroPool', message: 'Zero pool.' },
    },
  },
  cross_chain_oracle_relay: {
    contract: 'cross_chain_oracle_relay',
    enumName: 'OracleRelayError',
    errors: {
      1: {
        code: 1,
        name: 'AlreadyInitialized',
        message: 'Already initialized.',
      },
      2: { code: 2, name: 'NotInitialized', message: 'Not initialized.' },
      3: { code: 3, name: 'Unauthorized', message: 'Unauthorized.' },
      4: {
        code: 4,
        name: 'UnauthorizedRelayer',
        message: 'Unauthorized relayer.',
      },
      5: {
        code: 5,
        name: 'InvalidBlockHeader',
        message: 'Invalid block header.',
      },
      6: {
        code: 6,
        name: 'MerkleProofVerificationFailed',
        message: 'Merkle proof verification failed.',
      },
      7: { code: 7, name: 'PriceOutOfRange', message: 'Price out of range.' },
      8: {
        code: 8,
        name: 'InsufficientSignatures',
        message: 'Insufficient signatures.',
      },
      9: {
        code: 9,
        name: 'BlockAlreadyRelayed',
        message: 'Block already relayed.',
      },
    },
  },
  dutch_auction: {
    contract: 'dutch_auction',
    enumName: 'DutchAuctionError',
    errors: {
      1: {
        code: 1,
        name: 'AlreadyInitialized',
        message: 'Already initialized.',
      },
      2: { code: 2, name: 'NotInitialized', message: 'Not initialized.' },
      3: {
        code: 3,
        name: 'AuctionNotStarted',
        message: 'Auction not started.',
      },
      4: {
        code: 4,
        name: 'AuctionAlreadySettled',
        message: 'Auction already settled.',
      },
      5: { code: 5, name: 'CallNotEligible', message: 'Call not eligible.' },
      6: {
        code: 6,
        name: 'OracleDeadlineNotMet',
        message: 'Oracle deadline not met.',
      },
      7: { code: 7, name: 'Unauthorized', message: 'Unauthorized.' },
      8: { code: 8, name: 'InvalidParams', message: 'Invalid params.' },
      9: { code: 9, name: 'Overflow', message: 'Overflow.' },
      10: { code: 10, name: 'InvalidPrice', message: 'Invalid price.' },
      11: {
        code: 11,
        name: 'UnknownConditionType',
        message: 'Unknown condition type.',
      },
    },
  },
  gas_station: {
    contract: 'gas_station',
    enumName: 'GasStationError',
    errors: {
      1: {
        code: 1,
        name: 'NotInitialized',
        message:
          'A function requiring initialization was called before initialize.',
      },
      2: {
        code: 2,
        name: 'AlreadyInitialized',
        message: 'Initialize was called on an already-initialized contract.',
      },
      3: {
        code: 3,
        name: 'Unauthorized',
        message:
          'The caller-supplied admin address does not match the stored admin.',
      },
      4: {
        code: 4,
        name: 'InvalidWinningCutBps',
        message: 'winning_cut_bps exceeds 10 000 (100%).',
      },
      5: {
        code: 5,
        name: 'InvalidGasAmount',
        message:
          'max_gas_xlm (or an effective-stake gas estimate) is not positive, or would make the effective stake negative.',
      },
      6: {
        code: 6,
        name: 'UserNotSponsored',
        message:
          'User has no active sponsorship registered with this gas station.',
      },
      7: {
        code: 7,
        name: 'CallAlreadyProcessed',
        message: 'This call_id has already had its sponsored payout processed.',
      },
      8: {
        code: 8,
        name: 'InvalidWinningStake',
        message:
          'staker_winning_stake is 0 or negative; there is nothing to claim.',
      },
      9: {
        code: 9,
        name: 'Overflow',
        message:
          'An arithmetic operation overflowed; the transaction is reverted.',
      },
      10: {
        code: 10,
        name: 'InvalidRefillAmount',
        message: 'refill_gas_pool was called with a non-positive amount.',
      },
    },
  },
  governance: {
    contract: 'governance',
    enumName: 'GovernanceError',
    errors: {
      1: {
        code: 1,
        name: 'AlreadyInitialized',
        message: 'Already initialized.',
      },
      2: { code: 2, name: 'NotInitialized', message: 'Not initialized.' },
      3: { code: 3, name: 'Unauthorized', message: 'Unauthorized.' },
      4: { code: 4, name: 'ProposalNotFound', message: 'Proposal not found.' },
      5: { code: 5, name: 'AlreadyVoted', message: 'Already voted.' },
      6: { code: 6, name: 'ProposalInactive', message: 'Proposal inactive.' },
      7: {
        code: 7,
        name: 'VotingPeriodEnded',
        message: 'Voting period ended.',
      },
      8: {
        code: 8,
        name: 'InsufficientReputation',
        message: 'Insufficient reputation.',
      },
      9: { code: 9, name: 'AlreadyExecuted', message: 'Already executed.' },
      10: {
        code: 10,
        name: 'ProposalNotPassed',
        message: 'Proposal not passed.',
      },
      11: { code: 11, name: 'QuorumNotMet', message: 'Quorum not met.' },
      12: { code: 12, name: 'AlreadyDelegated', message: 'Already delegated.' },
      13: { code: 13, name: 'SelfDelegation', message: 'Self delegation.' },
    },
  },
  index_fund: {
    contract: 'index_fund',
    enumName: 'IndexFundError',
    errors: {
      1: {
        code: 1,
        name: 'AlreadyInitialized',
        message: 'Already initialized.',
      },
      2: { code: 2, name: 'NotInitialized', message: 'Not initialized.' },
      3: { code: 3, name: 'Unauthorized', message: 'Unauthorized.' },
      4: {
        code: 4,
        name: 'InsufficientLiquidity',
        message: 'Insufficient liquidity.',
      },
      5: { code: 5, name: 'InvalidAmount', message: 'Invalid amount.' },
      6: {
        code: 6,
        name: 'RebalanceTooFrequent',
        message: 'Rebalance too frequent.',
      },
      7: { code: 7, name: 'MarketNotFound', message: 'Market not found.' },
      8: {
        code: 8,
        name: 'NavCalculationError',
        message: 'Nav calculation error.',
      },
      9: { code: 9, name: 'ZeroSupply', message: 'Zero supply.' },
      10: { code: 10, name: 'FeeTooHigh', message: 'Fee too high.' },
      11: { code: 11, name: 'IndexFull', message: 'Index full.' },
      12: {
        code: 12,
        name: 'MarketNotResolved',
        message: 'Market not resolved.',
      },
      13: { code: 13, name: 'TransferFailed', message: 'Transfer failed.' },
    },
  },
  lending_pool: {
    contract: 'lending_pool',
    enumName: 'LendingPoolError',
    errors: {
      1: {
        code: 1,
        name: 'AlreadyInitialized',
        message: 'Already initialized.',
      },
      2: { code: 2, name: 'NotInitialized', message: 'Not initialized.' },
      3: { code: 3, name: 'InvalidAmount', message: 'Invalid amount.' },
      4: { code: 4, name: 'BelowMinDeposit', message: 'Below min deposit.' },
      5: { code: 5, name: 'PoolFull', message: 'Pool full.' },
      6: {
        code: 6,
        name: 'InsufficientShares',
        message: 'Insufficient shares.',
      },
      7: { code: 7, name: 'ZeroSupply', message: 'Zero supply.' },
      8: {
        code: 8,
        name: 'InsufficientLiquidity',
        message: 'Insufficient liquidity.',
      },
      9: { code: 9, name: 'Overflow', message: 'Overflow.' },
      10: { code: 10, name: 'PoolTooSmall', message: 'Pool too small.' },
      11: { code: 11, name: 'EmptyInput', message: 'Empty input.' },
      12: {
        code: 12,
        name: 'AllocationNotFound',
        message: 'Allocation not found.',
      },
      13: { code: 13, name: 'AlreadyHarvested', message: 'Already harvested.' },
      14: {
        code: 14,
        name: 'MarketNotResolved',
        message: 'Market not resolved.',
      },
      15: {
        code: 15,
        name: 'MarketCallFailed',
        message: 'Market call failed.',
      },
      16: { code: 16, name: 'Unauthorized', message: 'Unauthorized.' },
      17: { code: 17, name: 'InvalidBps', message: 'Invalid bps.' },
      18: { code: 18, name: 'InvalidConfig', message: 'Invalid config.' },
    },
  },
  oracle_marketplace: {
    contract: 'oracle_marketplace',
    enumName: 'OracleMarketplaceError',
    errors: {
      1: {
        code: 1,
        name: 'AlreadyInitialized',
        message: 'Already initialized.',
      },
      2: { code: 2, name: 'NotInitialized', message: 'Not initialized.' },
      3: { code: 3, name: 'Unauthorized', message: 'Unauthorized.' },
      4: {
        code: 4,
        name: 'OracleAlreadyRegistered',
        message: 'Oracle already registered.',
      },
      5: { code: 5, name: 'OracleNotFound', message: 'Oracle not found.' },
      6: { code: 6, name: 'OracleNotActive', message: 'Oracle not active.' },
      7: { code: 7, name: 'InsufficientStake', message: 'Insufficient stake.' },
      8: { code: 8, name: 'CooldownActive', message: 'Cooldown active.' },
      9: { code: 9, name: 'InvalidFee', message: 'Invalid fee.' },
      10: { code: 10, name: 'CallNotFound', message: 'Call not found.' },
      11: {
        code: 11,
        name: 'OracleNotSelectedForCall',
        message: 'Oracle not selected for call.',
      },
      12: { code: 12, name: 'AlreadyRated', message: 'Already rated.' },
      13: { code: 13, name: 'InvalidRating', message: 'Invalid rating.' },
    },
  },
  orderbook: {
    contract: 'orderbook',
    enumName: 'OrderbookError',
    errors: {
      1: {
        code: 1,
        name: 'AlreadyInitialized',
        message: 'Already initialized.',
      },
      2: { code: 2, name: 'NotInitialized', message: 'Not initialized.' },
      3: { code: 3, name: 'Unauthorized', message: 'Unauthorized.' },
      4: { code: 4, name: 'InvalidAmount', message: 'Invalid amount.' },
      5: { code: 5, name: 'InvalidPrice', message: 'Invalid price.' },
      6: { code: 6, name: 'OrderNotFound', message: 'Order not found.' },
      7: {
        code: 7,
        name: 'InsufficientBalance',
        message: 'Insufficient balance.',
      },
      8: { code: 8, name: 'SelfTrading', message: 'Self trading.' },
      9: {
        code: 9,
        name: 'MaxMatchesReached',
        message: 'Max matches reached.',
      },
    },
  },
  outcome_manager: {
    contract: 'outcome_manager',
    enumName: 'OutcomeError',
    errors: {
      1: {
        code: 1,
        name: 'AlreadyInitialized',
        message: 'Initialize was called on an already-initialized contract.',
      },
      2: {
        code: 2,
        name: 'InvalidQuorum',
        message: 'Quorum is 0 or exceeds the current oracle count.',
      },
      3: {
        code: 3,
        name: 'UnauthorizedOracle',
        message: 'The oracle public key is not in the trusted oracle set.',
      },
      4: {
        code: 4,
        name: 'AlreadySettled',
        message:
          'Quorum was already reached; the call outcome is already settled.',
      },
      5: {
        code: 5,
        name: 'DuplicateSubmission',
        message: 'This oracle already submitted a vote for the given call_id.',
      },
      6: {
        code: 6,
        name: 'InvalidOutcome',
        message: 'The outcome value is not within 1, outcome_count.',
      },
      7: {
        code: 7,
        name: 'CallNotSettled',
        message: 'claim_payout was called before quorum was reached.',
      },
      8: {
        code: 8,
        name: 'AlreadyClaimed',
        message:
          'The staker has already claimed their payout for this call_id.',
      },
      9: {
        code: 9,
        name: 'NothingToClaim',
        message: "The staker's winning stake is 0; there is nothing to claim.",
      },
      10: {
        code: 10,
        name: 'InvalidWinningStake',
        message:
          'total_winning_stake is 0 or negative; payout cannot be calculated.',
      },
      11: {
        code: 11,
        name: 'Overflow',
        message:
          'An arithmetic operation overflowed; the transaction is reverted.',
      },
      12: {
        code: 12,
        name: 'CallNotFinalized',
        message:
          'No pending outcome exists, or the dispute window has not yet elapsed.',
      },
      13: {
        code: 13,
        name: 'InvalidFeeBps',
        message: 'fee_bps exceeds 10 000 (100%).',
      },
      14: {
        code: 14,
        name: 'ContractPaused',
        message:
          'The contract is paused; submit_outcome and claim_payout are blocked.',
      },
      15: {
        code: 15,
        name: 'MaxOraclesReached',
        message: 'Adding an oracle would exceed the MAX_ORACLES cap of 20.',
      },
      16: {
        code: 16,
        name: 'SubmissionWindowExpired',
        message:
          "The oracle's timestamp is after call_end_ts + max_submission_delay.",
      },
      17: {
        code: 17,
        name: 'EmptyBatch',
        message: 'batch_claim_payouts was called with an empty stakers vec.',
      },
      18: {
        code: 18,
        name: 'LengthMismatch',
        message:
          'Stakers and stakes vecs passed to batch_claim_payouts differ in length.',
      },
      19: {
        code: 19,
        name: 'NotInitialized',
        message:
          'A function requiring initialization was called before initialize.',
      },
      20: {
        code: 20,
        name: 'FeeCollectorNotSet',
        message: 'A fee collector address has not been set yet.',
      },
      21: {
        code: 21,
        name: 'ObservationOutOfOrder',
        message:
          'A price observation was submitted out of chronological order.',
      },
      22: {
        code: 22,
        name: 'InsufficientPriceObservations',
        message:
          'compute_twap was called but fewer than 3 price observations are stored.',
      },
      23: {
        code: 23,
        name: 'NoPriceObservations',
        message:
          'compute_twap was called but no price observations exist for this call.',
      },
      24: {
        code: 24,
        name: 'ZeroTimeWindow',
        message:
          'All stored observations share the same timestamp; TWAP window is zero.',
      },
      25: {
        code: 25,
        name: 'RegistryNotSet',
        message:
          'The CallRegistry address has not been set in instance storage.',
      },
      26: {
        code: 26,
        name: 'DisputeWindowExpired',
        message:
          'dispute_outcome was called after the dispute window has already closed.',
      },
      27: {
        code: 27,
        name: 'FactoryNotSet',
        message: 'The factory address has not been set in instance storage.',
      },
      28: {
        code: 28,
        name: 'InvalidMarket',
        message:
          "The market address does not match the factory's registry for this call_id.",
      },
      29: {
        code: 29,
        name: 'ObservationOutsideWindow',
        message:
          "A price observation's timestamp falls outside call_end_ts - twap_window_secs, call_end_ts.",
      },
      30: {
        code: 30,
        name: 'NotRecoveryAgent',
        message:
          "claim_on_behalf was called by an address that is not the original winner's designated recovery address (or none has been set).",
      },
      31: {
        code: 31,
        name: 'RecoveryGracePeriodNotElapsed',
        message:
          'claim_on_behalf was called before recovery_grace_period has elapsed since the call was settled.',
      },
      32: {
        code: 32,
        name: 'DuplicateOracleObservation',
        message:
          'The same oracle submitted a second resolution observation for the same call_id via submit_resolution_observation.',
      },
    },
  },
  parlay_betting: {
    contract: 'parlay_betting',
    enumName: 'ParlayError',
    errors: {
      1: {
        code: 1,
        name: 'AlreadyInitialized',
        message: 'Already initialized.',
      },
      2: { code: 2, name: 'NotInitialized', message: 'Not initialized.' },
      3: { code: 3, name: 'InvalidLegCount', message: 'Invalid leg count.' },
      4: {
        code: 4,
        name: 'InvalidStakeAmount',
        message: 'Invalid stake amount.',
      },
      5: { code: 5, name: 'InvalidOutcome', message: 'Invalid outcome.' },
      6: { code: 6, name: 'ParlayNotFound', message: 'Parlay not found.' },
      7: { code: 7, name: 'ParlayNotActive', message: 'Parlay not active.' },
      8: { code: 8, name: 'LegNotResolved', message: 'Leg not resolved.' },
      9: { code: 9, name: 'MarketCallFailed', message: 'Market call failed.' },
      10: { code: 10, name: 'ContractPaused', message: 'Contract paused.' },
    },
  },
  prediction_market: {
    contract: 'prediction_market',
    enumName: 'MarketError',
    errors: {
      1: {
        code: 1,
        name: 'AlreadyInitialized',
        message: 'Already initialized.',
      },
      2: { code: 2, name: 'NotInitialized', message: 'Not initialized.' },
      3: {
        code: 3,
        name: 'InvalidStakeAmount',
        message: 'Invalid stake amount.',
      },
      4: { code: 4, name: 'InvalidEndTime', message: 'Invalid end time.' },
      5: { code: 5, name: 'CallNotFound', message: 'Call not found.' },
      6: { code: 6, name: 'CallEnded', message: 'Call ended.' },
      7: { code: 7, name: 'CallSettled', message: 'Call settled.' },
      8: { code: 8, name: 'InvalidPosition', message: 'Invalid position.' },
      9: { code: 9, name: 'Unauthorized', message: 'Unauthorized.' },
      10: { code: 10, name: 'ContractPaused', message: 'Contract paused.' },
      11: { code: 11, name: 'CallNotEnded', message: 'Call not ended.' },
      12: { code: 12, name: 'InvalidOutcome', message: 'Invalid outcome.' },
      13: {
        code: 13,
        name: 'InvalidOutcomeCount',
        message: 'Invalid outcome count.',
      },
      15: {
        code: 15,
        name: 'StakingCutoffActive',
        message: 'Staking cutoff active.',
      },
      16: { code: 16, name: 'InvalidCallId', message: 'Invalid call id.' },
      17: {
        code: 17,
        name: 'ReserveDiscrepancy',
        message: 'Reserve discrepancy.',
      },
      18: {
        code: 18,
        name: 'NotEligibleForBonus',
        message: 'Not eligible for bonus.',
      },
      19: {
        code: 19,
        name: 'Overflow',
        message: 'Checked arithmetic overflowed.',
      },
      20: {
        code: 20,
        name: 'OrderNotFound',
        message: 'No limit order exists with the given id.',
      },
      21: {
        code: 21,
        name: 'NotOrderOwner',
        message: 'Caller is not the owner of the limit order.',
      },
      22: {
        code: 22,
        name: 'InvalidTargetProbability',
        message:
          'target_implied_probability_bps is out of the valid 0..=10_000 range.',
      },
      23: {
        code: 23,
        name: 'InvalidOrderTTL',
        message:
          'ttl_secs is zero or exceeds the maximum allowed order lifetime.',
      },
      24: {
        code: 24,
        name: 'OrderNotExpired',
        message:
          'The order has not yet expired, so it cannot be force-refunded.',
      },
      25: {
        code: 25,
        name: 'InvalidRolloverPercentage',
        message: 'Rollover percentage exceeds 100% (10_000 bps).',
      },
      26: {
        code: 26,
        name: 'NoWinningStake',
        message: 'User has no stake on the winning outcome.',
      },
      27: {
        code: 27,
        name: 'RolloverInsufficientAmount',
        message:
          'Rollover amount is below the minimum stake for the new market.',
      },
      28: {
        code: 28,
        name: 'CallNotSettled',
        message: 'The call has not been settled yet.',
      },
    },
  },
  prediction_market_factory: {
    contract: 'prediction_market_factory',
    enumName: 'FactoryError',
    errors: {
      1: {
        code: 1,
        name: 'AlreadyInitialized',
        message: 'Already initialized.',
      },
      2: { code: 2, name: 'NotInitialized', message: 'Not initialized.' },
      3: { code: 3, name: 'Unauthorized', message: 'Unauthorized.' },
      4: {
        code: 4,
        name: 'InvalidStakeAmount',
        message: 'Invalid stake amount.',
      },
      5: { code: 5, name: 'InvalidEndTime', message: 'Invalid end time.' },
      6: {
        code: 6,
        name: 'InvalidOutcomeCount',
        message: 'Invalid outcome count.',
      },
      7: {
        code: 7,
        name: 'TokenNotWhitelisted',
        message: 'Token not whitelisted.',
      },
      8: { code: 8, name: 'ContractPaused', message: 'Contract paused.' },
      9: { code: 9, name: 'MarketWasmNotSet', message: 'Market wasm not set.' },
      10: { code: 10, name: 'MarketNotFound', message: 'Market not found.' },
      11: {
        code: 11,
        name: 'StrategyNotFound',
        message: 'Strategy not found.',
      },
      12: {
        code: 12,
        name: 'StrategyAlreadyExecuted',
        message: 'Strategy already executed.',
      },
      13: {
        code: 13,
        name: 'StrategyCancelled',
        message: 'Strategy cancelled.',
      },
      14: { code: 14, name: 'StrategyExpired', message: 'Strategy expired.' },
      15: { code: 15, name: 'TooManyActions', message: 'Too many actions.' },
      16: {
        code: 16,
        name: 'StrategyNotExecutable',
        message: 'Strategy not executable.',
      },
    },
  },
  prediction_market_futures: {
    contract: 'prediction_market_futures',
    enumName: 'FuturesError',
    errors: {
      1: {
        code: 1,
        name: 'AlreadyInitialized',
        message: 'Already initialized.',
      },
      2: { code: 2, name: 'NotInitialized', message: 'Not initialized.' },
      3: { code: 3, name: 'ContractNotFound', message: 'Contract not found.' },
      4: {
        code: 4,
        name: 'ContractAlreadySettled',
        message: 'Contract already settled.',
      },
      5: { code: 5, name: 'NoCounterparty', message: 'No counterparty.' },
      6: {
        code: 6,
        name: 'CounterpartyAlreadyAssigned',
        message: 'Counterparty already assigned.',
      },
      7: { code: 7, name: 'ContractExpired', message: 'Contract expired.' },
      8: {
        code: 8,
        name: 'ContractNotExpired',
        message: 'Contract not expired.',
      },
      9: { code: 9, name: 'InvalidMargin', message: 'Invalid margin.' },
      10: {
        code: 10,
        name: 'InvalidStrikeProbability',
        message: 'Invalid strike probability.',
      },
      11: { code: 11, name: 'InvalidExpiry', message: 'Invalid expiry.' },
      12: { code: 12, name: 'InvalidOutcome', message: 'Invalid outcome.' },
      13: { code: 13, name: 'MarketNotFound', message: 'Market not found.' },
      14: { code: 14, name: 'Overflow', message: 'Overflow.' },
      15: { code: 15, name: 'Unauthorized', message: 'Unauthorized.' },
    },
  },
  reputation_nft: {
    contract: 'reputation_nft',
    enumName: 'ReputationError',
    errors: {
      1: {
        code: 1,
        name: 'AlreadyInitialized',
        message: 'Already initialized.',
      },
      2: { code: 2, name: 'NotInitialized', message: 'Not initialized.' },
      3: { code: 3, name: 'Unauthorized', message: 'Unauthorized.' },
      4: {
        code: 4,
        name: 'BadgeAlreadyAwarded',
        message: 'Badge already awarded.',
      },
      5: {
        code: 5,
        name: 'TransferNotAllowed',
        message: 'Transfer not allowed.',
      },
      6: { code: 6, name: 'InvalidBadgeType', message: 'Invalid badge type.' },
    },
  },
  schelling_oracle: {
    contract: 'schelling_oracle',
    enumName: 'OracleError',
    errors: {
      1: {
        code: 1,
        name: 'AlreadyInitialized',
        message: 'Already initialized.',
      },
      2: { code: 2, name: 'NotInitialized', message: 'Not initialized.' },
      3: { code: 3, name: 'Unauthorized', message: 'Unauthorized.' },
      4: { code: 4, name: 'InvalidPeriod', message: 'Invalid period.' },
      5: { code: 5, name: 'InvalidBondBps', message: 'Invalid bond bps.' },
      6: { code: 6, name: 'InvalidOutcome', message: 'Invalid outcome.' },
      7: { code: 7, name: 'SameOutcome', message: 'Same outcome.' },
      8: {
        code: 8,
        name: 'InvalidPoolAmount',
        message: 'Invalid pool amount.',
      },
      9: {
        code: 9,
        name: 'InvalidBondAmount',
        message: 'Invalid bond amount.',
      },
      10: {
        code: 10,
        name: 'BondBelowMinimum',
        message: 'Bond below minimum.',
      },
      11: { code: 11, name: 'DisputeNotFound', message: 'Dispute not found.' },
      12: {
        code: 12,
        name: 'CommitPeriodEnded',
        message: 'Commit period ended.',
      },
      13: {
        code: 13,
        name: 'RevealPeriodNotStarted',
        message: 'Reveal period not started.',
      },
      14: {
        code: 14,
        name: 'RevealPeriodEnded',
        message: 'Reveal period ended.',
      },
      15: {
        code: 15,
        name: 'RevealPeriodNotEnded',
        message: 'Reveal period not ended.',
      },
      16: { code: 16, name: 'AlreadyCommitted', message: 'Already committed.' },
      17: {
        code: 17,
        name: 'NoCommitmentFound',
        message: 'No commitment found.',
      },
      18: { code: 18, name: 'AlreadyRevealed', message: 'Already revealed.' },
      19: {
        code: 19,
        name: 'CommitmentMismatch',
        message: 'Commitment mismatch.',
      },
      20: {
        code: 20,
        name: 'InvalidVoteOutcome',
        message: 'Invalid vote outcome.',
      },
      21: {
        code: 21,
        name: 'InvalidStakeAmount',
        message: 'Invalid stake amount.',
      },
      22: { code: 22, name: 'AlreadyResolved', message: 'Already resolved.' },
      23: { code: 23, name: 'TooManyVoters', message: 'Too many voters.' },
      24: { code: 24, name: 'Overflow', message: 'Overflow.' },
    },
  },
  tournament: {
    contract: 'tournament',
    enumName: 'TournamentError',
    errors: {
      1: {
        code: 1,
        name: 'AlreadyInitialized',
        message: 'Already initialized.',
      },
      2: { code: 2, name: 'NotInitialized', message: 'Not initialized.' },
      3: { code: 3, name: 'Unauthorized', message: 'Unauthorized.' },
      4: {
        code: 4,
        name: 'TournamentNotFound',
        message: 'Tournament not found.',
      },
      5: {
        code: 5,
        name: 'TournamentAlreadyFinalized',
        message: 'Tournament already finalized.',
      },
      6: {
        code: 6,
        name: 'TournamentNotFinalized',
        message: 'Tournament not finalized.',
      },
      7: { code: 7, name: 'InvalidTimeRange', message: 'Invalid time range.' },
      8: { code: 8, name: 'InvalidWeights', message: 'Invalid weights.' },
      9: {
        code: 9,
        name: 'MarketAlreadyEntered',
        message: 'Market already entered.',
      },
      10: {
        code: 10,
        name: 'TournamentNotActive',
        message: 'Tournament not active.',
      },
      11: {
        code: 11,
        name: 'InvalidPrizePool',
        message: 'Invalid prize pool.',
      },
      12: { code: 12, name: 'InvalidTopN', message: 'Invalid top n.' },
      13: {
        code: 13,
        name: 'ParticipantNotFound',
        message: 'Participant not found.',
      },
    },
  },
  yield_aggregator: {
    contract: 'yield_aggregator',
    enumName: 'AggregatorError',
    errors: {
      1: {
        code: 1,
        name: 'AlreadyInitialized',
        message: 'Already initialized.',
      },
      2: { code: 2, name: 'NotInitialized', message: 'Not initialized.' },
      3: { code: 3, name: 'Unauthorized', message: 'Unauthorized.' },
      4: { code: 4, name: 'InvalidAmount', message: 'Invalid amount.' },
      5: {
        code: 5,
        name: 'InsufficientShares',
        message: 'Insufficient shares.',
      },
      6: { code: 6, name: 'NoPayoutToClaim', message: 'No payout to claim.' },
      7: { code: 7, name: 'ZeroTotalAssets', message: 'Zero total assets.' },
    },
  },
};
